name: Sync and Compile Sing-box Rule-sets

on:
  schedule:
    # 每天凌晨 2:00 UTC 自动同步
    - cron: "0 2 * * *"
  workflow_dispatch: # 手动触发
  push:
    branches: [main, master]
    paths:
      - "sing-box/**/*.json"

jobs:
  sync-and-compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repository

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 稀疏检出源仓库 sing-box 目录
        run: |
          echo "🔄 开始稀疏检出 sing-box 目录..."
          # Create temporary directory
          mkdir -p temp-source
          cd temp-source

          # Initialize git repository
          git init
          git remote add origin https://github.com/SukkaLab/ruleset.skk.moe.git

          # Configure sparse checkout, only get sing-box directory
          git config core.sparseCheckout true
          echo "sing-box/*" > .git/info/sparse-checkout

          # Pull only the latest commit (depth 1, save time and bandwidth)
          git pull --depth=1 origin master

          # Get current commit hash
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "SOURCE_COMMIT=$CURRENT_COMMIT" >> $GITHUB_ENV
          echo "✅ 稀疏检出完成，提交哈希: ${CURRENT_COMMIT:0:7}"

          cd ..

      - name: 检查是否有更新
        id: check_updates
        run: |
          # Check last synced commit record
          if [ -f "last_sync_commit.txt" ]; then
            LAST_COMMIT=$(cat last_sync_commit.txt)
            echo "上次同步提交: $LAST_COMMIT"
          else
            LAST_COMMIT=""
            echo "首次同步"
          fi

          echo "当前源提交: $SOURCE_COMMIT"

          if [ "$LAST_COMMIT" != "$SOURCE_COMMIT" ]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
            echo "✅ 发现新的更新"
            
            # Calculate file changes
            if [ -d "sing-box" ]; then
              OLD_COUNT=$(find sing-box -name "*.json" -type f 2>/dev/null | wc -l)
            else
              OLD_COUNT=0
            fi
            NEW_COUNT=$(find temp-source/sing-box -name "*.json" -type f 2>/dev/null | wc -l)
            echo "OLD_FILE_COUNT=$OLD_COUNT" >> $GITHUB_ENV
            echo "NEW_FILE_COUNT=$NEW_COUNT" >> $GITHUB_ENV
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
            echo "ℹ️ 没有新的更新"
          fi

      - name: 同步 sing-box 目录
        if: steps.check_updates.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          echo "🔄 同步 sing-box 目录..."

          # Remove old sing-box directory
          rm -rf sing-box/

          # Copy new sing-box directory
          cp -r temp-source/sing-box ./

          # Record current synced commit
          echo "$SOURCE_COMMIT" > last_sync_commit.txt

          echo "✅ 同步完成"
          echo "📊 JSON 文件数量: $(find sing-box -name "*.json" -type f 2>/dev/null | wc -l)"

      - name: 安装 sing-box
        if: steps.check_updates.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          echo "⬇️ 安装 sing-box..."

          # Get latest version
          LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "📦 安装版本: $LATEST_VERSION"

          # Download and extract
          wget -q https://github.com/SagerNet/sing-box/releases/download/$LATEST_VERSION/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
          tar -xzf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
          sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/

          # Clean up downloaded files
          rm -rf sing-box-${LATEST_VERSION#v}-linux-amd64*

          # Verify installation
          sing-box version
          echo "✅ sing-box 安装完成"

      - name: 编译规则集文件
        if: steps.check_updates.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          echo "🔨 开始编译规则集文件..."

          # Count files
          json_files=$(find sing-box -name "*.json" -type f)
          json_count=$(echo "$json_files" | wc -l)
          echo "📁 找到 $json_count 个 JSON 规则文件"

          # Compile counters
          compiled_success=0
          compiled_failed=0

          # Compile each JSON file
          echo "$json_files" | while read -r json_file; do
            if [ -n "$json_file" ]; then
              echo "🔄 处理: $json_file"
              srs_file="${json_file%.json}.srs"
              
              if timeout 30 sing-box rule-set compile --output "$srs_file" "$json_file" 2>/dev/null; then
                file_size=$(ls -lh "$srs_file" | awk '{print $5}')
                echo "  ✅ 编译成功: $srs_file ($file_size)"
                compiled_success=$((compiled_success + 1))
              else
                echo "  ❌ 编译失败: $json_file"
                compiled_failed=$((compiled_failed + 1))
              fi
            fi
          done

          # Final statistics
          srs_count=$(find sing-box -name "*.srs" -type f 2>/dev/null | wc -l)
          echo ""
          echo "📊 编译统计:"
          echo "  - JSON 源文件: $json_count"
          echo "  - SRS 编译文件: $srs_count"
          echo "  - 编译成功: $compiled_success"
          echo "  - 编译失败: $compiled_failed"

          if [ "$compiled_failed" -gt 0 ]; then
            echo "⚠️ 有文件编译失败，但继续处理其他文件"
          fi

          echo "COMPILED_COUNT=$srs_count" >> $GITHUB_ENV

      - name: 生成 index.html 文档
        if: steps.check_updates.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          echo "📝 Generating index.html..."
          LAST_BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          # This prefix is taken directly from your provided index.html.
          # It implies a specific deployment path or domain configuration.
          HTML_LINK_PREFIX="/sing-box-ruleset-skk" # Adjust if your repo name or Pages path is different

          cat > index.html <<EOL
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <title>Sing-box Ruleset Server | Sukka (@SukkaW)</title>
            <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
            <link href="https://cdn.skk.moe/favicon.ico" rel="icon" type="image/ico">
            <link href="https://cdn.skk.moe/favicon/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180">
            <link href="https://cdn.skk.moe/favicon/android-chrome-192x192.png" rel="icon" type="image/png" sizes="192x192">
            <link href="https://cdn.skk.moe/favicon/favicon-32x32.png" rel="icon" type="image/png" sizes="32x32">
            <link href="https://cdn.skk.moe/favicon/favicon-16x16.png" rel="icon" type="image/png" sizes="16x16">
            <meta name="description" content="Sukka 自用的 Surge / Clash Premium 规则组 (Sing-box二进制版本)">
            <link rel="stylesheet" href="https://cdn.skk.moe/ruleset/css/21d8777a.css" />
            <meta property="og:title" content="Surge Ruleset | Sukka (@SukkaW)">
            <meta property="og:type" content="Website">
            <meta property="og:url" content="https://ruleset.skk.moe/">
            <meta property="og:image" content="https://cdn.skk.moe/favicon/android-chrome-192x192.png">
            <meta property="og:description" content="Sukka 自用的 Surge / Clash Premium 规则组 (Sing-box二进制版本)">
            <meta name="twitter:card" content="summary">
            <link rel="canonical" href="https://ruleset.skk.moe/">
          </head>
          <body>
            <main class="container">
              <h1>Sukka Ruleset Server</h1>
              <p>
                Made by <a href="https://skk.moe">Sukka</a> | <a href="https://github.com/SukkaW/Surge/">Source @ GitHub</a> |
                Licensed under <a href="/LICENSE" target="_blank">AGPL-3.0</a>
              </p>
              <p>Last Build: $LAST_BUILD_TIME</p>
              <br>
              <ul class="directory-list">
                <li class="folder">
                  sing-box
                  <ul>
          EOL

          if [ -d "sing-box" ]; then
            # Process subdirectories first
            find sing-box -mindepth 1 -maxdepth 1 -type d | sort | while read -r subdir_path; do
              subdir_name=$(basename "$subdir_path")
              echo "            <li class=\"folder\">" >> index.html
              echo "              $subdir_name" >> index.html
              echo "              <ul>" >> index.html
              find "$subdir_path" -name "*.srs" -type f | sort | while read -r srs_file; do
                # Path relative to the sing-box directory for the link
                relative_srs_path_to_singbox_dir="${srs_file#sing-box/}"
                file_name=$(basename "$srs_file")
                echo "                <li><a class=\"file directory-list-file\" href=\"$HTML_LINK_PREFIX/sing-box/$relative_srs_path_to_singbox_dir\">$file_name</a></li>" >> index.html
              done
              echo "              </ul>" >> index.html
              echo "            </li>" >> index.html
            done

            # Process files directly under sing-box (if any, though your example doesn't show this)
            find sing-box -maxdepth 1 -name "*.srs" -type f | sort | while read -r srs_file; do
              file_name=$(basename "$srs_file")
              echo "            <li><a class=\"file directory-list-file\" href=\"$HTML_LINK_PREFIX/sing-box/$file_name\">$file_name</a></li>" >> index.html
            done
          else
            echo "            <li>No sing-box rulesets found.</li>" >> index.html
          fi

          cat >> index.html <<EOL
                  </ul>
                </li>
              </ul>
            </main>
          </body>
          </html>
          EOL
          echo "✅ index.html documentation generated successfully."

      # MOVED CLEANUP STEP HERE - BEFORE COMMIT
      - name: 清理临时文件
        if: always() # Ensures cleanup even if previous steps fail, but critically before commit
        run: |
          echo "🧹 开始清理临时文件 temp-source..."
          rm -rf temp-source
          echo "🧹 清理完成"

      - name: 提交更新
        if: steps.check_updates.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
        env:
          SOURCE_COMMIT: ${{ env.SOURCE_COMMIT }}
          COMPILED_COUNT: ${{ env.COMPILED_COUNT }}
          OLD_FILE_COUNT: ${{ env.OLD_FILE_COUNT }}
          NEW_FILE_COUNT: ${{ env.NEW_FILE_COUNT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes (temp-source should be gone now)
          git add . 
          
          if git diff --staged --quiet; then
            echo "ℹ️ 没有更改需要提交"
          else
            commit_msg="🤖 自动同步并编译规则集

            📅 同步时间: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
            📝 源提交: ${SOURCE_COMMIT:0:7}
            📊 规则集数量: $COMPILED_COUNT
            📁 JSON文件变化: $OLD_FILE_COUNT → $NEW_FILE_COUNT

            自动处理内容:
            - 稀疏检出 sing-box 目录
            - 编译 JSON 规则集为二进制格式
            - 更新 index.html 文档" # Removed README.md update from commit message

            git commit -m "$commit_msg"
            git push
            echo "✅ 更新已提交并推送"
          fi

      - name: 生成构建摘要
        if: always()
        env:
          SOURCE_COMMIT: ${{ env.SOURCE_COMMIT }} # Ensure env vars are available
          COMPILED_COUNT: ${{ env.COMPILED_COUNT }}
        run: |
          if [ "${{ steps.check_updates.outputs.has_updates }}" == "true" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TOTAL_SIZE_RAW=$(du -sh sing-box 2>/dev/null)
            TOTAL_SIZE=$(echo "$TOTAL_SIZE_RAW" | cut -f1)
            if [ -z "$TOTAL_SIZE" ]; then TOTAL_SIZE="N/A"; fi
            echo "## 🎉 构建完成摘要" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| 项目 | 值 |" >> $GITHUB_STEP_SUMMARY
            echo "|------|-----|" >> $GITHUB_STEP_SUMMARY
            echo "| 🕐 构建时间 | $(date -u '+%Y-%m-%d %H:%M:%S UTC') |" >> $GITHUB_STEP_SUMMARY
            # Make sure SOURCE_COMMIT is available, if not, retrieve from env or an earlier step's output
            echo "| 📝 源提交 | [\`${SOURCE_COMMIT:0:7}\`](https://github.com/SukkaLab/ruleset.skk.moe/commit/$SOURCE_COMMIT) |" >> $GITHUB_STEP_SUMMARY
            echo "| 📊 编译文件 | $COMPILED_COUNT 个规则集 |" >> $GITHUB_STEP_SUMMARY
            echo "| 📁 总大小 | $TOTAL_SIZE |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "✅ **所有规则集已成功编译并更新！**" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ℹ️ 无需更新" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "当前规则集已是最新版本，无需重新编译。" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 上传编译结果
        if: steps.check_updates.outputs.has_updates == 'true' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-rulesets-${{ github.run_number }}
          path: |
            sing-box/**/*.srs
            index.html 
            last_sync_commit.txt
          retention-days: 30
          compression-level: 9
